import type { DropPoint, LngLat, Provider, ProviderProduct, Review, ServicePackage } from "./types";

export const PILOT = {
  id: "cankaya-cukurambar",
  city: "Ankara",
  label: "Çankaya · Çukurambar",
  /** OSM: Çukurambar Mahallesi centroid */
  center: { lng: 32.80286, lat: 39.90313 } satisfies LngLat,
  zoom: 15.7,
  radiusKm: 3,
  bounds: {
    west: 32.786,
    south: 39.894,
    east: 32.815,
    north: 39.913,
  },
};

/** Manuel konum seçimi (geo yoksa). Pilot mahalleler. */
export const NEIGHBORHOODS: { name: string; loc: LngLat }[] = [
  { name: "Çukurambar", loc: { lng: 32.80286, lat: 39.90313 } },
  { name: "Söğütözü", loc: { lng: 32.7902, lat: 39.9076 } },
  { name: "Kızılırmak", loc: { lng: 32.8091, lat: 39.9055 } },
];

export const PACKAGES: ServicePackage[] = [
  { id: "yikama", title: "Sadece yıkama", blurb: "Yıka, kurut, poşetle", pricePerPiece: 9 },
  { id: "katlama", title: "Yıkama + katlama", blurb: "Düzenli katlanmış teslim", pricePerPiece: 13 },
  { id: "tam", title: "Yıkama + ütü + katlama", blurb: "Tam paket", pricePerPiece: 18 },
];

const slots = [
  "Bugün 18:00–19:00",
  "Bugün 19:00–20:00",
  "Yarın 09:00–10:00",
  "Yarın 12:00–13:00",
  "Yarın 18:00–19:00",
];

export const PROVIDERS: Provider[] = [
  {
    id: "elif",
    name: "Elif Y.",
    neighborhood: "Çukurambar",
    loc: { lng: 32.79902, lat: 39.90163 },
    rating: 4.9,
    reviews: 86,
    packages: PACKAGES,
    capacity: 40,
    remaining: 24,
    hasDryer: true,
    express: true,
    trust: "kurucu",
    drops: ["kapi", "nokta"],
    slots,
    bio: "Kurucu hizmet veren. Makine kurutucu var, aynı gün bitirebiliyor.",
    workPhotos: [],
    recentReviews: [],
  },
  {
    id: "ayse",
    name: "Ayşe K.",
    neighborhood: "Söğütözü",
    loc: { lng: 32.7902, lat: 39.9076 },
    rating: 4.7,
    reviews: 41,
    packages: PACKAGES.filter((p) => p.id !== "tam").concat([
      { ...PACKAGES[2], pricePerPiece: 17 },
    ]),
    capacity: 28,
    remaining: 18,
    hasDryer: false,
    express: false,
    trust: "guvenilir",
    drops: ["kapi", "nokta"],
    slots: slots.slice(2),
    bio: "Kurutma ipte; yağmurlu günde ertesi sabaha kayabilir.",
    workPhotos: [],
    recentReviews: [],
  },
  {
    id: "merve",
    name: "Merve T.",
    neighborhood: "Kızılırmak",
    loc: { lng: 32.8091, lat: 39.9055 },
    rating: 4.8,
    reviews: 63,
    packages: PACKAGES.map((p) =>
      p.id === "tam" ? { ...p, pricePerPiece: 20 } : p,
    ),
    capacity: 36,
    remaining: 10,
    hasDryer: true,
    express: true,
    trust: "kurucu",
    drops: ["kapi", "nokta"],
    slots,
    bio: "Ütü ağırlıklı. Gömlek ve iş kıyafeti için tercih ediliyor.",
    workPhotos: [],
    recentReviews: [],
  },
  {
    id: "fatma",
    name: "Fatma D.",
    neighborhood: "Çukurambar",
    loc: { lng: 32.8014, lat: 39.8969 },
    rating: 4.6,
    reviews: 29,
    packages: [],
    products: [
      { id: "fatma:kisir", name: "Kısır", pricePerPerson: 45 },
      { id: "fatma:kurabiye", name: "Kurabiye", pricePerPerson: 28 },
    ] satisfies ProviderProduct[],
    categoryId: "davet",
    capacity: 22,
    remaining: 22,
    hasDryer: false,
    express: false,
    trust: "guvenilir",
    drops: ["nokta"],
    slots: slots.slice(1),
    bio: "Kısır ve ev kurabiyesi. Pasta yapmıyorum — o Hatice’de. Nötr noktada teslim.",
    workPhotos: [],
    recentReviews: [],
  },
  {
    id: "zeynep",
    name: "Zeynep A.",
    neighborhood: "Çukurambar",
    loc: { lng: 32.7964, lat: 39.8998 },
    rating: 4.5,
    reviews: 12,
    packages: PACKAGES.filter((p) => p.id !== "tam"),
    capacity: 18,
    remaining: 18,
    hasDryer: false,
    express: false,
    trust: "yeni",
    drops: ["nokta"],
    slots: slots.slice(2),
    bio: "İlk siparişlerde yalnızca nötr nokta. Yıkama ve katlama.",
    workPhotos: [],
    recentReviews: [],
  },
  {
    id: "hatice",
    name: "Hatice S.",
    neighborhood: "Kızılırmak",
    loc: { lng: 32.8096, lat: 39.9018 },
    rating: 4.8,
    reviews: 54,
    packages: [],
    products: [
      { id: "hatice:pasta", name: "Pasta", pricePerPerson: 65 },
      { id: "hatice:kisir", name: "Kısır", pricePerPerson: 42 },
    ] satisfies ProviderProduct[],
    categoryId: "davet",
    capacity: 32,
    remaining: 14,
    hasDryer: false,
    express: false,
    trust: "guvenilir",
    drops: ["kapi", "nokta"],
    slots,
    bio: "Pasta ve kısır. Kurabiye yapmıyorum — o Fatma veya Nurcan’da.",
    workPhotos: [],
    recentReviews: [],
  },
  {
    id: "nurcan",
    name: "Nurcan B.",
    neighborhood: "Çukurambar",
    loc: { lng: 32.8004, lat: 39.9087 },
    rating: 4.4,
    reviews: 18,
    packages: [],
    products: [
      { id: "nurcan:kurabiye", name: "Kurabiye", pricePerPerson: 22 },
    ] satisfies ProviderProduct[],
    categoryId: "davet",
    capacity: 20,
    remaining: 12,
    hasDryer: false,
    express: false,
    trust: "yeni",
    drops: ["nokta"],
    slots: slots.slice(0, 3),
    bio: "Sadece ev kurabiyesi. Kısır ve pasta yok. Kimlik doğrulaması tamam.",
    workPhotos: [],
    recentReviews: [],
  },
  {
    id: "gulsen",
    name: "Gülşen R.",
    neighborhood: "Çukurambar",
    loc: { lng: 32.8043, lat: 39.9049 },
    rating: 4.9,
    reviews: 101,
    packages: PACKAGES.map((p) => ({ ...p, pricePerPiece: p.pricePerPiece - 2 })),
    capacity: 48,
    remaining: 32,
    hasDryer: true,
    express: true,
    trust: "kurucu",
    drops: ["kapi", "nokta"],
    slots,
    bio: "En çok tekrar sipariş alan kurucu. Çocuklu aileler tercih ediyor.",
    workPhotos: [],
    recentReviews: [],
  },
].map((p) => ({ ...p, avatarUrl: `/avatars/${p.id}.jpg` })) as Provider[];

export const SEED_REVIEWS: Review[] = [
  {
    id: "rev-elif-1",
    providerId: "elif",
    orderId: null,
    rating: 5,
    body: "Gömlekler ütülü, kokusu temiz. Kapıda kimseyle karşılaşmadan teslim aldık.",
    author: "D.K.",
    createdAt: "2026-07-12T10:00:00.000Z",
  },
  {
    id: "rev-elif-2",
    providerId: "elif",
    orderId: null,
    rating: 5,
    body: "Aynı gün yetiştirdi. Nevresim iki parça sayıldı, şeffaf oldu.",
    author: "M.Y.",
    createdAt: "2026-06-28T18:20:00.000Z",
  },
  {
    id: "rev-gulsen-1",
    providerId: "gulsen",
    orderId: null,
    rating: 5,
    body: "Çocuk kıyafetlerini ayrı poşetledi. Tekrar bırakacağım.",
    author: "S.A.",
    createdAt: "2026-07-02T09:10:00.000Z",
  },
  {
    id: "rev-gulsen-2",
    providerId: "gulsen",
    orderId: null,
    rating: 4,
    body: "Katlaması düzgün. Nötr noktada 10 dk bekledim, o kadar.",
    author: "H.T.",
    createdAt: "2026-05-19T14:00:00.000Z",
  },
  {
    id: "rev-merve-1",
    providerId: "merve",
    orderId: null,
    rating: 5,
    body: "İş gömlekleri tam istediğim gibi. Ütü farkı belli oluyor.",
    author: "A.B.",
    createdAt: "2026-07-21T11:40:00.000Z",
  },
  {
    id: "rev-hatice-1",
    providerId: "hatice",
    orderId: null,
    rating: 5,
    body: "Doğum günü pastası tam saatinde geldi. Kişi başı netti.",
    author: "N.E.",
    createdAt: "2026-06-08T16:05:00.000Z",
  },
  {
    id: "rev-ayse-1",
    providerId: "ayse",
    orderId: null,
    rating: 4,
    body: "İpte kurutmuş, koku doğal. Yağmurda bir gün kaydı, haber verdi.",
    author: "C.R.",
    createdAt: "2026-07-30T08:15:00.000Z",
  },
  {
    id: "rev-fatma-1",
    providerId: "fatma",
    orderId: null,
    rating: 5,
    body: "Kısırı bol maydanozlu, kurabiye ayrı kutuda. Nötr noktada aldık.",
    author: "L.K.",
    createdAt: "2026-06-15T12:00:00.000Z",
  },
  {
    id: "rev-zeynep-1",
    providerId: "zeynep",
    orderId: null,
    rating: 4,
    body: "İlk siparişimdi, katlama özenliydi. Henüz ütü yok, o yüzden 4.",
    author: "P.S.",
    createdAt: "2026-08-03T19:30:00.000Z",
  },
  {
    id: "rev-nurcan-1",
    providerId: "nurcan",
    orderId: null,
    rating: 5,
    body: "Kurabiye taze, fındık alerjisi notunu okumuş. Tekrar sipariş.",
    author: "G.M.",
    createdAt: "2026-08-11T10:45:00.000Z",
  },
];

export const DROP_POINTS: DropPoint[] = [
  {
    id: "muhtarlik",
    name: "Çukurambar Muhtarlık",
    hint: "Öğretmenler Caddesi, giriş dolabı 08:00–21:00",
    loc: { lng: 32.80274, lat: 39.90363 },
  },
  {
    id: "cadde",
    name: "1427. Cadde",
    hint: "Restoran hattı, kafe önü teslim",
    loc: { lng: 32.8041, lat: 39.8996 },
  },
  {
    id: "park",
    name: "Kızılırmak Parkı",
    hint: "Park girişi, kafe terası",
    loc: { lng: 32.8102, lat: 39.9068 },
  },
  {
    id: "site",
    name: "Öğretmenler site kapısı",
    hint: "Güvenlik kulübesi, isim söylemen yeterli",
    loc: { lng: 32.7989, lat: 39.9051 },
  },
];

export function providerById(id: string) {
  return PROVIDERS.find((p) => p.id === id);
}

export function dropById(id: string) {
  return DROP_POINTS.find((d) => d.id === id);
}

export function trustLabel(tier: Provider["trust"]) {
  if (tier === "kurucu") return "Kurucu";
  if (tier === "guvenilir") return "Kapı açık";
  return "Nötr nokta";
}
