import type {
  DropPoint,
  LngLat,
  Provider,
  ProviderWash,
  Review,
  ServicePackage,
} from "./types";

export const PILOT = {
  id: "cankaya-cukurambar",
  city: "Ankara",
  label: "Çankaya · Çukurambar",
  /** OSM: Çukurambar Mahallesi centroid */
  center: { lng: 32.80286, lat: 39.90313 } satisfies LngLat,
  zoom: 15.7,
  radiusKm: 3,
  bounds: {
    west: 32.786,
    south: 39.894,
    east: 32.815,
    north: 39.913,
  },
};

/** Manuel konum seçimi (geo yoksa). Pilot mahalleler. */
export const NEIGHBORHOODS: { name: string; loc: LngLat }[] = [
  { name: "Çukurambar", loc: { lng: 32.80286, lat: 39.90313 } },
  { name: "Söğütözü", loc: { lng: 32.7902, lat: 39.9076 } },
  { name: "Kızılırmak", loc: { lng: 32.8091, lat: 39.9055 } },
];

export const PACKAGES: ServicePackage[] = [
  { id: "yikama", title: "Sadece yıkama", blurb: "Yıka, kurut, poşetle", pricePerPiece: 9 },
  { id: "katlama", title: "Yıkama + katlama", blurb: "Düzenli katlanmış teslim", pricePerPiece: 13 },
  { id: "tam", title: "Yıkama + ütü + katlama", blurb: "Tam paket", pricePerPiece: 18 },
];

const slots = [
  "Bugün 18:00–19:00",
  "Bugün 19:00–20:00",
  "Yarın 09:00–10:00",
  "Yarın 12:00–13:00",
  "Yarın 18:00–19:00",
];

const SEEDED_AVATARS = new Set([
  "elif",
  "ayse",
  "merve",
  "fatma",
  "zeynep",
  "hatice",
  "nurcan",
  "gulsen",
]);

export const PROVIDERS: Provider[] = [
{
    id: "elif",
    name: "Elif Y.",
    neighborhood: "Çukurambar",
    loc: { lng: 32.79902, lat: 39.90163 },
    rating: 4.9,
    reviews: 86,
    packages: PACKAGES,
    capacity: 40,
    remaining: 24,
    hasDryer: true,
    express: true,
    trust: "kurucu",
    drops: ["kapi", "nokta"],
    slots,
    bio: "Kurucu hizmet veren. Makine kurutucu var, aynı gün bitirebiliyor.",
    workPhotos: [],
    recentReviews: [],
  },
{
    id: "ayse",
    name: "Ayşe K.",
    neighborhood: "Söğütözü",
    loc: { lng: 32.7902, lat: 39.9076 },
    rating: 4.7,
    reviews: 41,
    packages: PACKAGES.filter((p) => p.id !== "tam").concat([
      { ...PACKAGES[2], pricePerPiece: 17 },
    ]),
    capacity: 28,
    remaining: 18,
    hasDryer: false,
    express: false,
    trust: "guvenilir",
    drops: ["kapi", "nokta"],
    slots: slots.slice(2),
    bio: "Kurutma ipte; yağmurlu günde ertesi sabaha kayabilir.",
    workPhotos: [],
    recentReviews: [],
  },
{
    id: "merve",
    name: "Merve T.",
    neighborhood: "Kızılırmak",
    loc: { lng: 32.8091, lat: 39.9055 },
    rating: 4.8,
    reviews: 63,
    packages: PACKAGES.map((p) =>
      p.id === "tam" ? { ...p, pricePerPiece: 20 } : p,
    ),
    capacity: 36,
    remaining: 10,
    hasDryer: true,
    express: true,
    trust: "kurucu",
    drops: ["kapi", "nokta"],
    slots,
    bio: "Ütü ağırlıklı. Gömlek ve iş kıyafeti için tercih ediliyor.",
    workPhotos: [],
    recentReviews: [],
  },
{
    id: "zeynep",
    name: "Zeynep A.",
    neighborhood: "Çukurambar",
    loc: { lng: 32.7964, lat: 39.8998 },
    rating: 4.5,
    reviews: 12,
    packages: PACKAGES.filter((p) => p.id !== "tam"),
    capacity: 18,
    remaining: 18,
    hasDryer: false,
    express: false,
    trust: "yeni",
    drops: ["nokta"],
    slots: slots.slice(2),
    bio: "İlk siparişlerde yalnızca gel al noktası. Yıkama ve katlama.",
    workPhotos: [],
    recentReviews: [],
  },
{
    id: "gulsen",
    name: "Gülşen R.",
    neighborhood: "Çukurambar",
    loc: { lng: 32.8043, lat: 39.9049 },
    rating: 4.9,
    reviews: 101,
    packages: PACKAGES.map((p) => ({ ...p, pricePerPiece: p.pricePerPiece - 2 })),
    capacity: 48,
    remaining: 32,
    hasDryer: true,
    express: true,
    trust: "kurucu",
    drops: ["kapi", "nokta"],
    slots,
    bio: "En çok tekrar sipariş alan kurucu. Çocuklu aileler tercih ediyor.",
    workPhotos: [],
    recentReviews: [],
  },
{
    id: "selin",
    name: "Selin M.",
    neighborhood: "Çukurambar",
    loc: { lng: 32.8051, lat: 39.9019 },
    rating: 4.3,
    reviews: 9,
    packages: PACKAGES.filter((p) => p.id !== "tam"),
    capacity: 16,
    remaining: 16,
    hasDryer: false,
    dryingType: "ip",
    express: false,
    trust: "yeni",
    drops: ["nokta"],
    slots: slots.slice(2),
    bio: "İpte kurutma, yıkama ve katlama. Ütü yok — o Elif veya Merve’de.",
    workPhotos: [],
    recentReviews: [],
  },
{
    id: "burak",
    name: "Burak E.",
    neighborhood: "Bahçelievler",
    loc: { lng: 32.8585, lat: 39.9255 },
    rating: 4.6,
    reviews: 33,
    packages: PACKAGES.map((p) => (p.id === "tam" ? { ...p, pricePerPiece: 19 } : p)),
    capacity: 30,
    remaining: 20,
    hasDryer: true,
    dryingType: "makine",
    express: true,
    trust: "guvenilir",
    drops: ["kapi", "nokta"],
    slots,
    bio: "Bahçelievler. Makine kurutucu, gömlek ütüsü. Çukurambar’a kapı veya nokta.",
    workPhotos: [],
    recentReviews: [],
  },
{
    id: "leyla",
    name: "Leyla C.",
    neighborhood: "Çayyolu",
    loc: { lng: 32.703, lat: 39.8895 },
    rating: 4.4,
    reviews: 21,
    packages: PACKAGES.filter((p) => p.id !== "tam").concat([{ ...PACKAGES[2], pricePerPiece: 16 }]),
    capacity: 22,
    remaining: 14,
    hasDryer: false,
    dryingType: "ip",
    express: false,
    trust: "yeni",
    drops: ["nokta"],
    slots: slots.slice(1),
    bio: "Çayyolu. İpte kurutma; yağmurda bir gün kayabilir. Gel al noktasında teslim.",
    workPhotos: [],
    recentReviews: [],
  },
{
    id: "okan",
    name: "Okan M.",
    neighborhood: "Çukurambar",
    loc: { lng: 32.8032, lat: 39.9018 },
    rating: 4.6,
    reviews: 22,
    packages: [],
    washes: [
      {
        id: "okan:dis",
        name: "Dış yıkama",
        job: "dis",
        vehicle: "otomobil",
        price: 180,
        includes: { dis: true, supurme: false, cam: true, torpido: false, jant: true, kurulama: true },
        durationMin: 25,
        maxPerDay: 12,
        booking: "musait",
        location: "Öğretmenler Caddesi otopark girişi",
        workHours: "Hafta içi 09:00–18:00",
        materials: "provider",
        notes: "Köpük + jant. İç süpürme ayrı.",
        isActive: true,
      },
      {
        id: "okan:icdis",
        name: "İç-dış paket",
        job: "icdis",
        vehicle: "otomobil",
        price: 280,
        includes: { dis: true, supurme: true, cam: true, torpido: true, jant: true, kurulama: true },
        durationMin: 45,
        maxPerDay: 8,
        booking: "musait",
        location: "Öğretmenler Caddesi otopark girişi",
        workHours: "Hafta içi 09:00–18:00",
        materials: "provider",
        isActive: true,
      },
    ] satisfies ProviderWash[],
    categoryId: "araba",
    capacity: 14,
    remaining: 10,
    hasDryer: false,
    express: false,
    trust: "guvenilir",
    drops: ["kapi", "nokta"],
    slots,
    bio: "Çukurambar. El yıkama, jant. SUV Serkan’da.",
    workPhotos: [],
    recentReviews: [],
  },
{
    id: "serkan",
    name: "Serkan Y.",
    neighborhood: "Bahçelievler",
    loc: { lng: 32.857, lat: 39.923 },
    rating: 4.5,
    reviews: 16,
    packages: [],
    washes: [
      {
        id: "serkan:suv",
        name: "SUV iç-dış",
        job: "icdis",
        vehicle: "suv",
        price: 350,
        includes: { dis: true, supurme: true, cam: true, torpido: true, jant: true, kurulama: true },
        durationMin: 60,
        maxPerDay: 6,
        booking: "randevu",
        location: "Bahçelievler site otoparkı",
        workHours: "10:00–19:00",
        materials: "provider",
        notes: "Yüksek araç. Randevu yaz.",
        isActive: true,
      },
    ] satisfies ProviderWash[],
    categoryId: "araba",
    capacity: 10,
    remaining: 7,
    hasDryer: false,
    express: false,
    trust: "yeni",
    drops: ["kapi", "nokta"],
    slots: slots.slice(0, 4),
    bio: "Bahçelievler. SUV ve hafif ticari. Sedan Okan’da daha ucuz.",
    workPhotos: [],
    recentReviews: [],
  },
{
    id: "volkan",
    name: "Volkan E.",
    neighborhood: "Çayyolu",
    loc: { lng: 32.706, lat: 39.887 },
    rating: 4.4,
    reviews: 11,
    packages: [],
    washes: [
      {
        id: "volkan:ic",
        name: "İç temizlik",
        job: "ic",
        vehicle: "otomobil",
        price: 220,
        includes: { dis: false, supurme: true, cam: true, torpido: true, jant: false, kurulama: false },
        durationMin: 40,
        maxPerDay: 8,
        booking: "randevu",
        location: "Çayyolu 8. Cadde, site kapısı",
        workHours: "Hafta içi 11:00–18:00",
        materials: "provider",
        notes: "Dış yıkama yok. Koltuk şampuanı extra.",
        isActive: true,
      },
      {
        id: "volkan:ticari",
        name: "Hafif ticari dış",
        job: "dis",
        vehicle: "ticari",
        price: 260,
        includes: { dis: true, supurme: false, cam: true, torpido: false, jant: true, kurulama: true },
        durationMin: 35,
        maxPerDay: 5,
        booking: "musait",
        location: "Çayyolu 8. Cadde, site kapısı",
        workHours: "Hafta içi 11:00–18:00",
        materials: "provider",
        isActive: true,
      },
    ] satisfies ProviderWash[],
    categoryId: "araba",
    capacity: 12,
    remaining: 8,
    hasDryer: false,
    express: false,
    trust: "yeni",
    drops: ["kapi", "nokta"],
    slots: slots.slice(1, 4),
    bio: "Çayyolu. İç detay ve ticari dış. Randevu iç işte.",
    workPhotos: [],
    recentReviews: [],
  },
].map((p) => ({
  ...p,
  avatarUrl: SEEDED_AVATARS.has(p.id) ? `/avatars/${p.id}.jpg` : undefined,
})) as Provider[];

export const SEED_REVIEWS: Review[] = [
  {
    id: "rev-elif-1",
    providerId: "elif",
    orderId: null,
    rating: 5,
    body: "Gömlekler ütülü, kokusu temiz. Kapıda kimseyle karşılaşmadan teslim aldık.",
    author: "D.K.",
    createdAt: "2026-07-12T10:00:00.000Z",
  },
  {
    id: "rev-elif-2",
    providerId: "elif",
    orderId: null,
    rating: 5,
    body: "Aynı gün yetiştirdi. Nevresim iki parça sayıldı, şeffaf oldu.",
    author: "M.Y.",
    createdAt: "2026-06-28T18:20:00.000Z",
  },
  {
    id: "rev-gulsen-1",
    providerId: "gulsen",
    orderId: null,
    rating: 5,
    body: "Çocuk kıyafetlerini ayrı poşetledi. Tekrar bırakacağım.",
    author: "S.A.",
    createdAt: "2026-07-02T09:10:00.000Z",
  },
  {
    id: "rev-gulsen-2",
    providerId: "gulsen",
    orderId: null,
    rating: 4,
    body: "Katlaması düzgün. Gel al noktasında 10 dk bekledim, o kadar.",
    author: "H.T.",
    createdAt: "2026-05-19T14:00:00.000Z",
  },
  {
    id: "rev-merve-1",
    providerId: "merve",
    orderId: null,
    rating: 5,
    body: "İş gömlekleri tam istediğim gibi. Ütü farkı belli oluyor.",
    author: "A.B.",
    createdAt: "2026-07-21T11:40:00.000Z",
  },
  {
    id: "rev-hatice-1",
    providerId: "hatice",
    orderId: null,
    rating: 5,
    body: "Doğum günü pastası tam saatinde geldi. Kişi başı netti.",
    author: "N.E.",
    createdAt: "2026-06-08T16:05:00.000Z",
  },
  {
    id: "rev-ayse-1",
    providerId: "ayse",
    orderId: null,
    rating: 4,
    body: "İpte kurutmuş, koku doğal. Yağmurda bir gün kaydı, haber verdi.",
    author: "C.R.",
    createdAt: "2026-07-30T08:15:00.000Z",
  },
  {
    id: "rev-fatma-1",
    providerId: "fatma",
    orderId: null,
    rating: 5,
    body: "Kısırı bol maydanozlu, kurabiye ayrı kutuda. Gel al noktasında aldık.",
    author: "L.K.",
    createdAt: "2026-06-15T12:00:00.000Z",
  },
  {
    id: "rev-zeynep-1",
    providerId: "zeynep",
    orderId: null,
    rating: 4,
    body: "İlk siparişimdi, katlama özenliydi. Henüz ütü yok, o yüzden 4.",
    author: "P.S.",
    createdAt: "2026-08-03T19:30:00.000Z",
  },
  {
    id: "rev-nurcan-1",
    providerId: "nurcan",
    orderId: null,
    rating: 5,
    body: "Kurabiye taze, fındık alerjisi notunu okumuş. Tekrar sipariş.",
    author: "G.M.",
    createdAt: "2026-08-11T10:45:00.000Z",
  },
  {
    id: "rev-guler-1",
    providerId: "guler",
    orderId: null,
    rating: 5,
    body: "Paça aynı gün bitti, ütü düzgün. Fermuar da tuttu.",
    author: "E.S.",
    createdAt: "2026-08-18T14:20:00.000Z",
  },
  {
    id: "rev-hasan-1",
    providerId: "hasan",
    orderId: null,
    rating: 5,
    body: "Telefon ekranı net fiyat, aynı gün teslim. Garanti kâğıdı verdi.",
    author: "R.D.",
    createdAt: "2026-08-20T11:05:00.000Z",
  },
  {
    id: "rev-emre-1",
    providerId: "emre",
    orderId: null,
    rating: 5,
    body: "Windows format temiz, sürücüler tam. USB’yi de verdi.",
    author: "K.S.",
    createdAt: "2026-08-16T15:10:00.000Z",
  },
  {
    id: "rev-okan-1",
    providerId: "okan",
    orderId: null,
    rating: 5,
    body: "Dış yıkama 25 dk, jant temiz. Otoparkta bekledim.",
    author: "T.A.",
    createdAt: "2026-08-22T10:20:00.000Z",
  },
  {
    id: "rev-deniz-1",
    providerId: "deniz",
    orderId: null,
    rating: 5,
    body: "Anahtarı 15 dk’da kapıya bıraktı. Kodla teslim.",
    author: "N.K.",
    createdAt: "2026-08-24T11:05:00.000Z",
  },
  {
    id: "rev-selda-1",
    providerId: "selda",
    orderId: null,
    rating: 5,
    body: "Çim düzgün, yapraklar poşetlendi. Site bahçesinde 1 saat.",
    author: "E.B.",
    createdAt: "2026-08-25T09:40:00.000Z",
  },
  {
    id: "rev-hakan-1",
    providerId: "hakan",
    orderId: null,
    rating: 5,
    body: "Yurtiçi’den aldı, site kapısına 25 dk’da bıraktı. Kodla teslim.",
    author: "S.Y.",
    createdAt: "2026-08-26T14:20:00.000Z",
  },
  {
    id: "rev-pinar-1",
    providerId: "pinar",
    orderId: null,
    rating: 5,
    body: "PDF’i attım, 15 dk’da A4 çıktı hazırdı. Adresinden aldım.",
    author: "M.K.",
    createdAt: "2026-08-27T11:10:00.000Z",
  },
  {
    id: "rev-gulay-1",
    providerId: "gulay",
    orderId: null,
    rating: 5,
    body: "Salça kıvamı tam. İki kavanozu adresinden aldım, kışlık bitti.",
    author: "E.D.",
    createdAt: "2026-08-20T16:40:00.000Z",
  },
  {
    id: "rev-serap-1",
    providerId: "serap",
    orderId: null,
    rating: 5,
    body: "Orta halıyı 3 günde teslim etti. Adresinden aldım, koku yok.",
    author: "N.K.",
    createdAt: "2026-08-22T15:20:00.000Z",
  },
  {
    id: "rev-seda-1",
    providerId: "seda",
    orderId: null,
    rating: 5,
    body: "Kızımın matematik ödevini iki derste toparladı. Evde, sakin.",
    author: "A.Y.",
    createdAt: "2026-08-23T17:10:00.000Z",
  },
  {
    id: "rev-dilara-1",
    providerId: "dilara",
    orderId: null,
    rating: 5,
    body: "Speaking’i iki görüşmede açıldı. Evde, sakin.",
    author: "M.K.",
    createdAt: "2026-08-24T16:40:00.000Z",
  },
  {
    id: "rev-defne-1",
    providerId: "defne",
    orderId: null,
    rating: 5,
    body: "Annemin mezarı bakımlı, çiçek taze. Fotoğraf da geldi. Eve kimse girmedi.",
    author: "S.A.",
    createdAt: "2026-08-25T11:20:00.000Z",
  },
  {
    id: "rev-burak-1",
    providerId: "burak",
    orderId: null,
    rating: 5,
    body: "Bahçelievler’den geldi, gömlekler tam. Biraz uzak ama ütü fark eder.",
    author: "Y.K.",
    createdAt: "2026-08-14T09:40:00.000Z",
  },
  {
    id: "rev-dilek-1",
    providerId: "dilek",
    orderId: null,
    rating: 5,
    body: "Dikmen’den pasta geldi, yazı doğru, krema bozulmamış.",
    author: "B.N.",
    createdAt: "2026-08-09T16:30:00.000Z",
  },
  {
    id: "rev-tulay-1",
    providerId: "tulay",
    orderId: null,
    rating: 5,
    body: "Oran’da prova yaptık, elbise oturdu. Süre baştan söyledi.",
    author: "F.A.",
    createdAt: "2026-07-27T13:15:00.000Z",
  },
];

export const DROP_POINTS: DropPoint[] = [
  {
    id: "muhtarlik",
    name: "Çukurambar Muhtarlık",
    hint: "Öğretmenler Caddesi, giriş dolabı 08:00–21:00",
    loc: { lng: 32.80274, lat: 39.90363 },
  },
  {
    id: "cadde",
    name: "1427. Cadde",
    hint: "Restoran hattı, kafe önü teslim",
    loc: { lng: 32.8041, lat: 39.8996 },
  },
  {
    id: "park",
    name: "Kızılırmak Parkı",
    hint: "Park girişi, kafe terası",
    loc: { lng: 32.8102, lat: 39.9068 },
  },
  {
    id: "site",
    name: "Öğretmenler site kapısı",
    hint: "Güvenlik kulübesi, isim söylemen yeterli",
    loc: { lng: 32.7989, lat: 39.9051 },
  },
];

export function providerById(id: string) {
  return PROVIDERS.find((p) => p.id === id);
}

export function dropById(id: string) {
  return DROP_POINTS.find((d) => d.id === id);
}

export function trustLabel(tier: Provider["trust"]) {
  if (tier === "kurucu") return "Kurucu";
  if (tier === "guvenilir") return "Kapı açık";
  return "Gel al noktası";
}
