import type { LngLat, Provider, Review, ServicePackage } from "./types";

export const PILOT = {
  id: "cankaya-cukurambar",
  city: "Ankara",
  label: "Çankaya · Çukurambar",
  /** OSM: Çukurambar Mahallesi centroid */
  center: { lng: 32.80286, lat: 39.90313 } satisfies LngLat,
  zoom: 15.7,
  radiusKm: 3,
  bounds: {
    west: 32.786,
    south: 39.894,
    east: 32.815,
    north: 39.913,
  },
};

/** Manuel konum seçimi (geo yoksa). Pilot mahalleler. */
export const NEIGHBORHOODS: { name: string; loc: LngLat }[] = [
  { name: "Çukurambar", loc: { lng: 32.80286, lat: 39.90313 } },
  { name: "Söğütözü", loc: { lng: 32.7902, lat: 39.9076 } },
  { name: "Kızılırmak", loc: { lng: 32.8091, lat: 39.9055 } },
];

export const PACKAGES: ServicePackage[] = [
  { id: "yikama", title: "Sadece yıkama", blurb: "Yıka, kurut, poşetle", pricePerPiece: 9 },
  { id: "katlama", title: "Yıkama + katlama", blurb: "Düzenli katlanmış teslim", pricePerPiece: 13 },
  { id: "tam", title: "Yıkama + ütü + katlama", blurb: "Tam paket", pricePerPiece: 18 },
];

const slots = [
  "Bugün 18:00–19:00",
  "Bugün 19:00–20:00",
  "Yarın 09:00–10:00",
  "Yarın 12:00–13:00",
  "Yarın 18:00–19:00",
];

const SEEDED_AVATARS = new Set(["elif", "ayse", "merve", "zeynep", "gulsen"]);

export const PROVIDERS: Provider[] = [
{
    id: "elif",
    name: "Elif Y.",
    neighborhood: "Çukurambar",
    loc: { lng: 32.79902, lat: 39.90163 },
    rating: 4.9,
    reviews: 86,
    packages: PACKAGES,
    hasDryer: true,
    express: true,
    trust: "kurucu",
    drops: ["kapi"],
    slots,
    bio: "Kurucu hizmet veren. Makine kurutucu var, aynı gün bitirebiliyor.",
    workPhotos: [],
    recentReviews: [],
  },
{
    id: "ayse",
    name: "Ayşe K.",
    neighborhood: "Söğütözü",
    loc: { lng: 32.7902, lat: 39.9076 },
    rating: 4.7,
    reviews: 41,
    packages: PACKAGES.filter((p) => p.id !== "tam").concat([
      { ...PACKAGES[2], pricePerPiece: 17 },
    ]),
    hasDryer: false,
    express: false,
    trust: "guvenilir",
    drops: ["kapi"],
    slots: slots.slice(2),
    bio: "Kurutma ipte; yağmurlu günde ertesi sabaha kayabilir.",
    workPhotos: [],
    recentReviews: [],
  },
{
    id: "merve",
    name: "Merve T.",
    neighborhood: "Kızılırmak",
    loc: { lng: 32.8091, lat: 39.9055 },
    rating: 4.8,
    reviews: 63,
    packages: PACKAGES.map((p) =>
      p.id === "tam" ? { ...p, pricePerPiece: 20 } : p,
    ),
    hasDryer: true,
    express: true,
    trust: "kurucu",
    drops: ["kapi"],
    slots,
    bio: "Ütü ağırlıklı. Gömlek ve iş kıyafeti için tercih ediliyor.",
    workPhotos: [],
    recentReviews: [],
  },
{
    id: "zeynep",
    name: "Zeynep A.",
    neighborhood: "Çukurambar",
    loc: { lng: 32.7964, lat: 39.8998 },
    rating: 4.5,
    reviews: 12,
    packages: PACKAGES.filter((p) => p.id !== "tam"),
    hasDryer: false,
    express: false,
    trust: "yeni",
    drops: ["kapi"],
    slots: slots.slice(2),
    bio: "Kapıda teslim. Yıkama ve katlama.",
    workPhotos: [],
    recentReviews: [],
  },
{
    id: "gulsen",
    name: "Gülşen R.",
    neighborhood: "Çukurambar",
    loc: { lng: 32.8043, lat: 39.9049 },
    rating: 4.9,
    reviews: 101,
    packages: PACKAGES.map((p) => ({ ...p, pricePerPiece: p.pricePerPiece - 2 })),
    hasDryer: true,
    express: true,
    trust: "kurucu",
    drops: ["kapi"],
    slots,
    bio: "En çok tekrar sipariş alan kurucu. Çocuklu aileler tercih ediyor.",
    workPhotos: [],
    recentReviews: [],
  },
{
    id: "selin",
    name: "Selin M.",
    neighborhood: "Çukurambar",
    loc: { lng: 32.8051, lat: 39.9019 },
    rating: 4.3,
    reviews: 9,
    packages: PACKAGES.filter((p) => p.id !== "tam"),
    hasDryer: false,
    dryingType: "ip",
    express: false,
    trust: "yeni",
    drops: ["kapi"],
    slots: slots.slice(2),
    bio: "İpte kurutma, yıkama ve katlama. Ütü yok — o Elif veya Merve’de.",
    workPhotos: [],
    recentReviews: [],
  },
{
    id: "burak",
    name: "Burak E.",
    neighborhood: "Bahçelievler",
    loc: { lng: 32.8585, lat: 39.9255 },
    rating: 4.6,
    reviews: 33,
    packages: PACKAGES.map((p) => (p.id === "tam" ? { ...p, pricePerPiece: 19 } : p)),
    hasDryer: true,
    dryingType: "makine",
    express: true,
    trust: "guvenilir",
    drops: ["kapi"],
    slots,
    bio: "Bahçelievler. Makine kurutucu, gömlek ütüsü. Çukurambar’a kapı teslim.",
    workPhotos: [],
    recentReviews: [],
  },
{
    id: "leyla",
    name: "Leyla C.",
    neighborhood: "Çayyolu",
    loc: { lng: 32.703, lat: 39.8895 },
    rating: 4.4,
    reviews: 21,
    packages: PACKAGES.filter((p) => p.id !== "tam").concat([{ ...PACKAGES[2], pricePerPiece: 16 }]),
    hasDryer: false,
    dryingType: "ip",
    express: false,
    trust: "yeni",
    drops: ["kapi"],
    slots: slots.slice(1),
    bio: "Çayyolu. İpte kurutma; yağmurda bir gün kayabilir. Kapıda teslim.",
    workPhotos: [],
    recentReviews: [],
  },
].map((p) => ({
  ...p,
  categoryId: "camasir" as const,
  avatarUrl: SEEDED_AVATARS.has(p.id) ? `/avatars/${p.id}.jpg` : undefined,
})) as Provider[];

export const SEED_REVIEWS: Review[] = [
  {
    id: "rev-elif-1",
    providerId: "elif",
    orderId: null,
    rating: 5,
    body: "Gömlekler ütülü, kokusu temiz. Kapıda kimseyle karşılaşmadan teslim aldık.",
    author: "D.K.",
    createdAt: "2026-07-12T10:00:00.000Z",
  },
  {
    id: "rev-elif-2",
    providerId: "elif",
    orderId: null,
    rating: 5,
    body: "Aynı gün yetiştirdi. Nevresim iki parça sayıldı, şeffaf oldu.",
    author: "M.Y.",
    createdAt: "2026-06-28T18:20:00.000Z",
  },
  {
    id: "rev-gulsen-1",
    providerId: "gulsen",
    orderId: null,
    rating: 5,
    body: "Çocuk kıyafetlerini ayrı poşetledi. Tekrar bırakacağım.",
    author: "S.A.",
    createdAt: "2026-07-02T09:10:00.000Z",
  },
  {
    id: "rev-gulsen-2",
    providerId: "gulsen",
    orderId: null,
    rating: 4,
    body: "Katlaması düzgün. Kapıda teslim 10 dk sürdü, o kadar.",
    author: "H.T.",
    createdAt: "2026-05-19T14:00:00.000Z",
  },
  {
    id: "rev-merve-1",
    providerId: "merve",
    orderId: null,
    rating: 5,
    body: "İş gömlekleri tam istediğim gibi. Ütü farkı belli oluyor.",
    author: "A.B.",
    createdAt: "2026-07-21T11:40:00.000Z",
  },
  {
    id: "rev-ayse-1",
    providerId: "ayse",
    orderId: null,
    rating: 4,
    body: "İpte kurutmuş, koku doğal. Yağmurda bir gün kaydı, haber verdi.",
    author: "C.R.",
    createdAt: "2026-07-30T08:15:00.000Z",
  },
  {
    id: "rev-zeynep-1",
    providerId: "zeynep",
    orderId: null,
    rating: 4,
    body: "İlk siparişimdi, katlama özenliydi. Henüz ütü yok, o yüzden 4.",
    author: "P.S.",
    createdAt: "2026-08-03T19:30:00.000Z",
  },
  {
    id: "rev-burak-1",
    providerId: "burak",
    orderId: null,
    rating: 5,
    body: "Bahçelievler’den geldi, gömlekler tam. Biraz uzak ama ütü fark eder.",
    author: "Y.K.",
    createdAt: "2026-08-14T09:40:00.000Z",
  },
];

export function providerById(id: string) {
  return PROVIDERS.find((p) => p.id === id);
}

export function trustLabel(tier: Provider["trust"]) {
  if (tier === "kurucu") return "Kurucu";
  if (tier === "guvenilir") return "Kapı açık";
  return "Yeni komşu";
}
